name: Generate diff

on:
  push:
    branches: [master, test-ci]

jobs:
  diff:
    runs-on: ubuntu-20.04
    container:
      image: plass/mdtopdf:include-fonts
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup secret key
        env:
          SECRET_KEY: ${{ secrets.TEST_KEY }}
        run: |
          echo "$SECRET_KEY" > secret_key
          chmod 600 secret_key
          echo "get /usr/local/texlive/texmf-local/tex/aizu/U-AizuGT.cls" | sftp -i secret_key -oStrictHostKeyChecking=no s1250117@sshgate.u-aizu.ac.jp
      - name: Replace "JY1" to "JY2"
        run: |
          sed -i -e "s/JY1/JY2/g" U-AizuGT.cls
      - name: Generate diff
        run: |
          scripts/diff.sh thesis.tex
      - name: Commit
        run: |
          git config --local user.email "github_actions@example.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "generate diff [skip ci]"
          git push origin ${GITHUB_REF##*/}
