name: Generate diff

on:
  push:
    branches: [master, test-ci]

jobs:
  diff:
    runs-on: ubuntu-20.04
    container:
      image: plass/mdtopdf:include-fonts
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Fetch document class file
        uses: appleboy/scp-action@master
        with: 
          host: sshgate.u-aizu.ac.jp
          username: s1250117
          key: ${{ secrets.SSH_KEY }}
          key_path: ~/ssh/fetch_dc_rsa
          source: "image.png"
          # source: "/usr/local/texlive/texmf-local/tex/aizu/U-AizuGT.cls"
          target: "tests"
          strip_components: 6
      - name: Generate diff
        run: |
          scripts/diff.sh thesis.tex
      - name: Commit
        run: |
          git config --local user.email "github_actions@example.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "generate diff [skip ci]"
          git push origin ${GITHUB_REF##*/}
