name: Generate diff

on:
  push:
    branches: [master, test-ci]

jobs:
  diff:
    runs-on: ubuntu-20.04
    container:
      image: plass/mdtopdf:include-fonts
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: fetch_dc_rsa
          known_hosts: ${{ secrets.KNOWN_HOST }}
          config: |
            Host aizu
              HostName sshgate.u-aizu.ac.jp
              User s1250117
              Ciphers aes256-cbc
              IdentityFile  ~/.ssh/aizu_rsa
      - name: Fetch document class file
        run: |
          ls ~/.ssh
          cat ~/.ssh/config
          ssh -oStrictHostKeyChecking=no aizu "pwd"
        # scripts/fetch-dc.sh s1250117
        # echo "get /usr/local/texlive/texmf-local/tex/aizu/U-AizuGT.cls" | sftp -i ~/.ssh/fetch_dc_rsa s1250117@sshgate.u-aizu.ac.jp
        # scp u-aizu:/usr/local/texlive/texmf-local/tex/aizu/U-AizuGT.cls .
        # uses: appleboy/scp-action@master
        # with: 
        #   host: sshgate.u-aizu.ac.jp
        #   username: s1250117
        #   key: ${{ secrets.SSH_KEY }}
        #   key_path: /github/home/.ssh/fetch_dc_rs
        #   source: "image.png"
        #   # source: "/usr/local/texlive/texmf-local/tex/aizu/U-AizuGT.cls"
        #   target: "tests"
        #   strip_components: 6
      - name: Generate diff
        run: |
          scripts/diff.sh thesis.tex
      - name: Commit
        run: |
          git config --local user.email "github_actions@example.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "generate diff [skip ci]"
          git push origin ${GITHUB_REF##*/}
