name: Generate diff

on:
  push:
    branches: [master]

jobs:
  diff:
    runs-on: ubuntu-20.04
    container:
      image: plass/mdtopdf:include-fonts
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.SSH_KEY }}
          name: github_action
          known_hosts: ${{secrets.HOST_NAME}}
      - name: Fetch Document Class
        run: |
          scripts/fetch-documentclass.sh s1250117
      - name: Generate diff
        run: |
          scripts/diff.sh thesis.tex
      - name: Commit
        run: |
          git config --local user.email "github_actions@example.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "generate diff [skip ci]"
          git push origin ${GITHUB_REF##*/}
